Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2024-12, with the labels that each got.

#267 Add installation instructions to README.md
  README.md
Labels: documentation

#270 API improvements (KMP friendly)
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Dsl.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtIssuer.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtPresent.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/DecoyTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaimsTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Utils.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleRecreateClaims01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
Labels: bug, improvement

#273 Major Pub API update
  README.md
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtIssuer.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtPresent.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/DecoyTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/JwsJsonSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegrationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Sample.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/StandardSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleIssueSdJw01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwt01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleRecreateClaims01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: improvement, breaks pub api

#285 SdJwtRecreateClaimsOps
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtPresent.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaimsTest.kt
Labels: improvement

#287 Remove reference to JsonPointer from README.
  README.md
Labels: documentation

#289 Replace junit packages with kotlin.test
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/DisclosedClaimSetTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/ClaimPathTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SelectPathTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/TypeMetadataTest.kt
Labels: improvement

#290 Add comments to DSL
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Dsl.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
Labels: documentation

#292 Stack safe SelectPath
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SelectPath.kt
Labels: improvement

#291 Parameterized verifier
  README.md
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegrationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Sample.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleIssuanceSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: improvement

#297 Require 'vct' claim during SD-JWT-VC verification.
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcJwtProcessor.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: bug, sd-jwt-vc spec alignment

#296 Unify SD-JWT Issuance & Presentation into a single class
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtDigest.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtIssuer.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtPresent.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/DecoyTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/DisclosedClaimSetTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/JwsJsonSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegrationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Sample.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/StandardSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Utils.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleIssuanceSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwt01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleReadMeTest01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleRecreateClaims01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
Labels: improvement, breaks pub api

#298 Define the methods of SdJwtVerifier and SdJwtVcVerifier more appropriately.
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Sample.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleIssuanceSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: bug, improvement, sd-jwt spec alignment, sd-jwt-vc spec alignment, breaks pub api

#302 Properly calculate the index of array elements during recreation.
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt
Labels: bug

#303 Makes various operations stack-safe
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SelectPath.kt
Labels: improvement

#306 Improve deployment of array decoys.
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtFactory.kt
Labels: improvement
