Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2024-11, with the labels that each got.

#235 Do not consider `kid` when selecting/filtering keys resolved from a DID Document
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcJwtProcessor.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
Labels: feature

#239 Corrected some misspellings and changed some wording (#238)
  Module.md
  README.md
  docs/examples/example-flat-sd-jwt-01.md
  docs/examples/example-structured-sd-jwt-01.md
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PresentationTest.kt
Labels: documentation

#251 Fix signature verification of Key Binding JWTs signed using OctetKeyPairs/EdDSA
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcJwtProcessor.kt
Labels: feature

#253 Support SD-JWT-VC Type metadata
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Disclosure.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Dsl.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtDigest.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtPresent.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Specs.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/ClaimPath.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/GetSdJwtVcIssuerMetadataOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetadata.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcJwtProcessor.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SelectPath.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/TypeMetadata.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/ClaimValidationsTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVCIssuer.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/StandardSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Utils.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwt01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/ClaimPathTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetaDataFetcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SelectPathTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/TypeMetadataTest.kt
Labels: feature, sd-jwt-vc spec alignment

#264 Fix keyBindingVerifier npe
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
Labels: bug
