Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2024-05, with the labels that each got.

#187 Replaced ECKey with AsymmetricJWK to get PublickKey
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
Labels: bug

#190 Make verifications suspendable.
  README.md
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegrationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Sample.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVCIssuer.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleIssuanceSdJwtVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwtVerification01.kt
Labels: feature

#191 Add SD-JWT-VC verifier
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/DnsUri.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/Ktor.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/X509SubjectAlternativeName.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/DnsUriTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetaDataFetcherTest.kt
Labels: feature, SD-JWT-VC
