Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2024-09, with the labels that each got.

#218 Update JWS JSON support
  Module.md
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/JwsJsonSerialization.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExamplePresentationSdJwtVerification01.kt
Labels: draft12, sd-jwt spec alignment

#220 fix: solve double tilda problem
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/StandardSerializationTest.kt
Labels: bug

#221 Update README
  README.md
Labels: documentation
