Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2025-05, with the labels that each got.

#334 Pass SD-JWT VC claimset as an extra parameter when checking X5C trust
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
Labels: feature, improvement, breaks pub api

#333 Refactor code to be more KMP friendly
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOpsJavaAndAndroidExt.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Hashes.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/JvmAndAndroidPlatform.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Platform.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Random.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/GetSdJwtVcIssuerJwkSetKtorOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/GetSdJwtVcIssuerMetadataOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/NimbusSdJwtVcFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetadata.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/TypeMetadata.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuerMetaDataFetcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: other, improvement, breaks pub api

#340 Upgrade dependency check plugin to 12.1.1
  gradle/libs.versions.toml
Labels: other

#337 Improve error message for InvalidDisclosures
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Utils.kt
Labels: feature, breaks pub api

#348 Add RetrieveTypeMetadata with default impl
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/RetrieveTypeMetadata.kt
Labels: feature

#353 Introduce `FirstNotNullOfOrNull`
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/FirstNotNullOfOrNull.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/FunctionExt.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/ResolveTypeMetadata.kt
Labels: feature
