Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2025-03, with the labels that each got.

#288 Replace Java Base64 with kotlin.io
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Base64UrlNoPadding.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Deprecated.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/Disclosure.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DisclosureDigest.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/JwtBase64.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SaltProvider.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtDigest.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
Labels: improvement

#319 Upgrade gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#321 Improve error handling and introduce more fine-grained errors for SD-JWT VC verification.
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtSerialization.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: improvement, breaks pub api

#323 Improve KeyBinding JWT validation errors
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifierVerifyPresentationTest.kt
Labels: feature, improvement, breaks pub api
