Repository eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt, pull requests merged in 2025-06, with the labels that each got.

#365 Refactor `SdJwtVcVerifierFactory` and enable `SdJwtDefinition` veriifcation for SD-JWT VC.
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOpsJavaAndAndroidExt.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/NimbusSdJwtVcVerifierFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierFactory.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: feature, improvement, breaks pub api

#366 Add support for Json Schema validation in `SdJwtVcVerifier`
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/dsl/def/DefinitionBasedSdJwtVcValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/JsonSchemaValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/NimbusSdJwtVcVerifierFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierFactory.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: feature, sd-jwt-vc spec alignment, breaks pub api

#367 Added some helper function for SdJwtDefinition
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/dsl/def/SdJwtDefinition.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/dsl/def/FindElementTest.kt
Labels: improvement

#368 Issue fix and integration tests
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/dsl/def/DefinitionBasedSdJwtVcValidator.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierIntegrationTest.kt
  src/test/resources/pid_arf_v18.json
Labels: bug, feature, improvement

#369 DefinitionBasedSdJwtObjectBuilder - SD-JWT-VC templates
  README.md
  docs/dsl.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/dsl/values/DefinitionBasedSdJwtObjectBuilder.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/dsl/values/SdJwtElement.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Utils.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/dsl/values/TemplateTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleIssueSdJw01.kt
Labels: feature

#370 Rework recreate claims
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/DefaultSdJwtOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtPresentationOps.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/SdJwtVerifier.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/dsl/def/DefinitionBasedSdJwtVcValidator.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaimsTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SdJsonElementArrayElementTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/SpecExamples.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/Utils.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/dsl/values/TemplateTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleRecreateClaims01.kt
Labels: improvement, breaks pub api

#376 Introduce `TypeMetadataPolicy`
  Module.md
  README.md
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/NimbusSdJwtVcVerifierFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierFactory.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/KeyBindingTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/PidDevVerificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/examples/ExampleSdJwtVcVerification01.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcIssuanceTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierIntegrationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifierTest.kt
Labels: feature, breaks pub api
